#!/usr/bin/env python3
"""Render the repository's current-state page from revision-control records."""

from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ACTIVE_BATCH = ROOT / "workflow/ACTIVE_BATCH"
STATUS = ROOT / "STATUS.md"
BATCH_ID_RE = re.compile(r"REV-\d{3}")
SHA_RE = re.compile(r"[0-9a-f]{40}")
NEXT_TASK_STATES = {"ready", "blocked", "in_progress", "complete", "not_started"}


def resolve_active_batch(root: Path = ROOT) -> tuple[str, Path]:
    """Resolve the one-line active-batch pointer to its manifest."""
    pointer = root / "workflow/ACTIVE_BATCH"
    batch_id = pointer.read_text(encoding="utf-8").strip()
    if not BATCH_ID_RE.fullmatch(batch_id):
        raise ValueError("workflow/ACTIVE_BATCH must contain exactly one REV-### identifier")
    manifest_path = root / "workflow/batches" / f"{batch_id}.json"
    if not manifest_path.is_file():
        raise FileNotFoundError(f"active batch manifest not found: {manifest_path}")
    return batch_id, manifest_path


def load_state(root: Path = ROOT) -> dict:
    """Load and validate the explicit metadata needed to render status."""
    batch_id, path = resolve_active_batch(root)
    with path.open(encoding="utf-8") as stream:
        manifest = json.load(stream)
    if manifest.get("batch_id") != batch_id:
        raise ValueError("active batch pointer and manifest batch_id disagree")

    operations = manifest.get("operations", {})
    current_key = manifest.get("current_operation")
    if current_key not in operations:
        raise ValueError("current_operation must identify an operation in the manifest")
    for key, operation in operations.items():
        sha = operation.get("merge_sha")
        if sha is not None and not (isinstance(sha, str) and SHA_RE.fullmatch(sha)):
            raise ValueError(f"operations.{key}.merge_sha must be a lowercase 40-character SHA")

    for name, repository in manifest.get("repositories", {}).items():
        for field in ("baseline_sha", "merge_sha"):
            sha = repository.get(field)
            if sha is not None and not (isinstance(sha, str) and SHA_RE.fullmatch(sha)):
                raise ValueError(f"repositories.{name}.{field} must be null or a lowercase 40-character SHA")

    handoff = root / manifest.get("latest_handoff", "")
    if not handoff.is_file():
        raise FileNotFoundError(f"latest handoff not found: {handoff}")

    next_task = manifest.get("next_task")
    if not isinstance(next_task, dict):
        raise ValueError("next_task must be an object describing the current authorized work")
    if next_task.get("state") not in NEXT_TASK_STATES:
        raise ValueError(f"next_task.state must be one of {sorted(NEXT_TASK_STATES)}")
    for field in ("id", "title", "description"):
        if not isinstance(next_task.get(field), str) or not next_task[field].strip():
            raise ValueError(f"next_task.{field} must be a non-empty string")
    authorization_files = next_task.get("authorization_files", [])
    if not isinstance(authorization_files, list) or not authorization_files:
        raise ValueError("next_task.authorization_files must be a non-empty list")
    for relative_path in authorization_files:
        if not isinstance(relative_path, str) or not (root / relative_path).is_file():
            raise FileNotFoundError(f"next-task authorization file not found: {relative_path}")

    return manifest


def _items(values: list[str]) -> list[str]:
    return [f"- {value}" for value in values] or ["- None recorded."]


def _inline_ids(values: list[str]) -> str:
    return ", ".join(f"`{item}`" for item in values) if values else "None recorded."


def _inline_links(values: list[str]) -> str:
    return ", ".join(f"[`{item}`]({item})" for item in values)


def render_status(manifest: dict) -> str:
    """Return deterministic Markdown for a validated active manifest."""
    operations = manifest["operations"]
    operation = operations[manifest["current_operation"]]
    repositories = manifest["repositories"]
    access = manifest["source_access"]
    stages = manifest["stages"]
    next_task = manifest["next_task"]
    lines = [
        "# PCC system status",
        "",
        "> Generated by `python scripts/render_system_status.py` from `workflow/ACTIVE_BATCH`",
        "> and its resolved batch manifest. Do not edit this page manually.",
        "",
        "## Current revision",
        "",
        f"- **Active batch:** `{manifest['batch_id']}`",
        f"- **Batch title:** {manifest['title']}",
        f"- **Batch status:** `{manifest['status']}`",
        f"- **Last completed operation:** {operation['title']}",
        f"- **Current evidence operation merge SHA:** `{operation['merge_sha']}` (PR #{operation['pr']})",
        f"- **Proposal baseline:** `{repositories['proposal']['baseline_sha']}`",
        f"- **Prototype baseline:** `{repositories['prototype']['baseline_sha']}`",
        "",
        "## Current authorized work",
        "",
        f"- **Task:** {next_task['title']} (`{next_task['id']}`)",
        f"- **Task state:** `{next_task['state']}`",
        f"- **Description:** {next_task['description']}",
        f"- **Authorization files:** {_inline_links(next_task['authorization_files'])}",
        "",
        "A `ready` task state means work may proceed now. Downstream proposal stages may",
        "remain gated without blocking the current evidence task.",
        "",
        "## Completed evidence operations",
        "",
    ]
    for value in operations.values():
        lines.append(
            f"- **{value['title']}:** `{value['state']}` (PR #{value['pr']}, merge `{value['merge_sha']}`)"
        )
    lines.extend([
        "",
        "## Source-access controls",
        "",
        f"- **Exact full texts available:** {_inline_ids(access['exact_full_texts'])}",
        f"- **Proxy comparators available:** {_inline_ids(access['proxy_comparators'])}",
        f"- **Exact-source access gaps:** {_inline_ids(access['exact_source_gaps'])}",
        "",
        "Source intake and substantive mechanism audit are distinct operations. An audit is",
        "recorded as complete only when its merged artifacts and handoff are present.",
        "",
        "## Downstream stage gates",
        "",
    ])
    for key in ("prompt_c", "prompt_d", "closure"):
        lines.append(f"- **{stages[key]['title']}:** `{stages[key]['state']}`")
    lines.extend([
        "",
        "These gate states describe later stages. They are not the state of the current task",
        f"when **Task state** above is `{next_task['state']}`.",
        "",
        "## Control state",
        "",
        f"- **Current work state:** `{next_task['state']}`.",
        f"- **Next authorized task:** {manifest['next_authorized_task']}",
        f"- **Latest handoff:** [`{manifest['latest_handoff']}`]({manifest['latest_handoff']})",
        f"- **Prompt C downstream gate:** `{stages['prompt_c']['state']}`.",
        "",
        "### Unresolved limitations",
        "",
        *_items(manifest["limitations"]),
        "",
        "### Repository housekeeping",
        "",
        *_items(manifest["housekeeping"]),
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    manifest = load_state(ROOT)
    STATUS.write_text(render_status(manifest), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
